#
# URL settings
#
# these need to be adjusted depending on target platform,
# local Jekyll need different settings than github-pages :-(

# deployment with github-pages on custom domain
#url: http://docs.arc42.org
#imageurl: http://docs.arc42.org/images


url: http://localhost
imageurl: http://localhost:4000/images
baseurl:

# temporary deployment on arc42.github.io/faq
# -----------------------------------------------------
#url: http://arc42.github.io
#baseurl: "/faq"

#
# basic settings
#
title: Patterns 42
description: The incomplete guide to architecture patterns.
avatar: /assets/img/arc42logosquare.png
favicon: /assets/img/arc42-favicon.svg
language: en

str_search: Search

#
# want (disqus) comments?
#
disqus: true

#
# want subtle ads (on post-pages)
#
show-subtle-ads: true


# Analytics
analytics:
  google:
    tracking_id : 

#
# Icons
#
icons:
  rss: false
  email: false
  github: arc42
  twitter: gernotstarke
  google_plus: 105917203908419102125
  stack_overflow: arc42
  slack: arc42

#
# Prettify url.
#
permalink: pretty


#
# Gems.
#
gems:
  - jekyll-paginate
  - jemoji

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude: [Gemfile, Gemfile.lock, LICENSE, README.md, originals]
