version: '2'

services:
  jekyll:
    build: .
    image: gernotstarke:patterns-jekyll
    command: jekyll serve --trace --host 0.0.0.0 --watch --incremental
    environment:
      - JEKYLL_ENV=development
#      - PAGES_REPO_NWO=gernotstarke/esabuch.de-site
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - $PWD/_config-dev.yml:/srv/jekyll/_config.yml
